name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

  functional:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.5.0

      - name: Start OPA
        run: opa run -s -a localhost:8181 fixtures &

      - name: Run tests
        run: uv run pytest oslo_policy_opa/tests/functional.py
